### ISSUE TITLE
The variable "centriod_address" in python file  

### ISSUE THREAD

**Issue by zhangzm0128** [syxiaa/ball-k-means#2]
The variable "centriod_address" in python file  maybe has some spelling mistakes.
I think that you maybe want to use "centroid" instead of "centriod", which is "重心" in Chinese.

**Comment by BaiTuu** [comment]
请问楼主有成功运行代码吗？我运行的时候遇到下面这个问题：
D:\Software\anaconda3\envs\py36\python.exe D:/test/ball-k-means-master/ball-k-means-master/PythonVersion/win_kmeans++_python.py
Traceback (most recent call last):
File "D:/test/ball-k-means-master/ball-k-means-master/PythonVersion/win_kmeans++_python.py", line 54, in
"D:\test\ball-k-means-master\ball-k-means-master\data+centers(1)\centroids\four2.csv")
File "D:/test/ball-k-means-master/ball-k-means-master/PythonVersion/win_kmeans++_python.py", line 28, in fit
dll.ball_kmeans_cent(s1.encode('utf-8'), dataptr, lenth, isRing, detail, s2.encode('utf-8'))
OSError: exception: integer divide by zero
然后我进行debug，发现dll.ball_kmeans_cent()这个函数提示“Cannot find declaration to go to”，望楼主能帮忙解答一下。

**Comment by panjialong12** [comment]
> 
I encountered the same problem, how did you finally get it to work?
