### ISSUE TITLE
Ring or no ring?

### ISSUE THREAD

**Issue by ShenfeiPei** [syxiaa/ball-k-means#3]
What's the difference between the ring version and the no ring version?
Which one is the algorithm used in the published paper?

**Comment by BaiTuu** [comment]
请问楼主有成功运行代码吗？我运行的时候遇到下面这个问题：
D:\Software\anaconda3\envs\py36\python.exe D:/test/ball-k-means-master/ball-k-means-master/PythonVersion/win_kmeans++_python.py
Traceback (most recent call last):
  File "D:/test/ball-k-means-master/ball-k-means-master/PythonVersion/win_kmeans++_python.py", line 54, in <module>
    "D:\\test\\ball-k-means-master\\ball-k-means-master\\data+centers(1)\\centroids\\four2.csv")
  File "D:/test/ball-k-means-master/ball-k-means-master/PythonVersion/win_kmeans++_python.py", line 28, in fit
    dll.ball_kmeans_cent(s1.encode('utf-8'), dataptr, lenth, isRing, detail, s2.encode('utf-8'))
OSError: exception: integer divide by zero
然后我进行debug，发现dll.ball_kmeans_cent()这个函数提示“Cannot find declaration to go to”，望楼主能帮忙解答一下。

**Comment by ShenfeiPei** [comment]
同学您好：
       不好意思，我是在linux下运行的c++版本，数据用的是Epile。目前没有出现错误。
       您的这个问题，我觉得是数据的问题，调用应该没错。建议检查下数据的路径，书写格式，文件编码等。

**Comment by wwangdefeng** [comment]
> 请问楼主有成功运行代码吗？我运行的时候遇到下面这个问题： D:\Software\anaconda3\envs\py36\python.exe D:/test/ball-k-means-master/ball-k-means-master/PythonVersion/win_kmeans++_python.py Traceback (most recent call last): File "D:/test/ball-k-means-master/ball-k-means-master/PythonVersion/win_kmeans++_python.py", line 54, in "D:\test\ball-k-means-master\ball-k-means-master\data+centers(1)\centroids\four2.csv") File "D:/test/ball-k-means-master/ball-k-means-master/PythonVersion/win_kmeans++_python.py", line 28, in fit dll.ball_kmeans_cent(s1.encode('utf-8'), dataptr, lenth, isRing, detail, s2.encode('utf-8')) OSError: exception: integer divide by zero 然后我进行debug，发现dll.ball_kmeans_cent()这个函数提示“Cannot find declaration to go to”，望楼主能帮忙解答一下。

你好，我在运行windows版本时也遇到了同样的问题，请问您是如何已经解决这个问题了吗？
